name: Replace text
description: Replace text
inputs:
  file:
    description: File path
    required: true
  find:
    description: Text to find
    required: true
  replace:
    description: Text to replace
    required: true

runs:
  using: composite
  steps:
  - run: |
      ${{ inputs.find }}
      $content = Get-Content ${{ inputs.file }} -raw
      for ($i = 0; $i -lt ${{ inputs.find }}.length; $i++) {
        $content = $content -replace (${{ inputs.find }}[$i] -replace [Environment]::NewLine, "`n"), ${{ inputs.replace }}[$i]
      }
      Set-Content ${{ inputs.file }} $content
    shell: pwsh
