name: Replace text
description: Replace text
inputs:
  file:
    description: File path
    required: true
  find:
    description: Text to find
    required: true
  replace:
    description: Text to replace
    required: true

  runs:
    using: "composite"
    steps:
      run: (Get-Content ${{ inputs.file }}) -replace [regex]::Escape(${{ inputs.find }}), ${{ inputs.replace }} | Set-Content ${{ inputs.file }}
