name: Replace text
description: Replace text
inputs:
  file:
    description: File path
    required: true
  find:
    description: Text to find
    required: true
  replace:
    description: Text to replace
    required: true

runs:
  using: composite
  steps:
  - run: |
      $file = Get-Content ${{ inputs.file }} -raw
      $find = ${{ inputs.find }}.split('\n')
      $replace = ${{ inputs.replace }}.split('\n')
      for ($i = 0; $i -lt $find.length; $i++) {
        $file = $file.replace($find[$i], $replace[$i])
      }
      Set-Content ${{ inputs.file }} $file
      (Get-Content ${{ inputs.file }} -raw)
    shell: pwsh
