name: Replace text
description: Replace text
inputs:
  file:
    description: File path
    required: true
  find:
    description: Text to find
    required: true
  replace:
    description: Text to replace
    required: true

runs:
  using: composite
  steps:
  - run: |
      echo ${{ inputs.find }}
      echo Get-Content ${{ inputs.file }} -raw).replace('${{ inputs.find }}', '${{ inputs.replace }}')
      Set-Content ${{ inputs.file }} (Get-Content ${{ inputs.file }} -raw).replace('${{ inputs.find }}', '${{ inputs.replace }}')
      echo Get-Content ${{ inputs.file }} -raw).replace('${{ inputs.find }}', '${{ inputs.replace }}')
    shell: pwsh
