name: Replace text
description: Replace text
inputs:
  file:
    description: File path
    required: true
  find:
    description: Text to find
    required: true
  replace:
    description: Text to replace
    required: true

runs:
  using: composite
  steps:
  - run: |
      Set-Content ${{ inputs.file }} (Get-Content ${{ inputs.file }} -raw).replace('${{ inputs.find }}'.replace([Environment]::NewLine, [char]10), '${{ inputs.replace }}')
      Get-Content ${{ inputs.file }} -raw
    shell: pwsh
