name: Replace text
description: Replace text
inputs:
  file:
    description: File path
    required: true
  find:
    description: Text to find
    required: true
  replace:
    description: Text to replace
    required: true

runs:
  using: composite
  steps:
  - run: |
        $find = @"
        ${{ inputs.find }}
        "@
        $replace = @"
        ${{ inputs.replace }}
        "@
      Set-Content ${{ inputs.file }} (Get-Content ${{ inputs.file }} -raw).replace($find, $replace)
      (Get-Content ${{ inputs.file }} -raw)
    shell: pwsh
