name: Replace text
description: Replace text
inputs:
  file:
    description: File path
    required: true
  find:
    description: Text to find
    required: true
  replace:
    description: Text to replace
    required: true

runs:
  using: composite
  steps:
  - run: |
      $content = Get-Content ${{ inputs.file }} -raw
      $find = '${{ inputs.find }}'.split([Environment]::NewLine)
      $replace = '${{ inputs.replace }}'.split([Environment]::NewLine)
      for ($i = 0; $i -lt $find.Length; $i++) {
        echo $i
        echo $find[$i]
        $content = $content.replace($find[$i], $replace[$i])
      }
      Set-Content ${{ inputs.file }} $content
      Get-Content ${{ inputs.file }} -raw
    shell: pwsh
