name: Replace text
description: Replace text
inputs:
  file:
    description: File path
    required: true
  find:
    description: Text to find
    required: true
  replace:
    description: Text to replace
    required: true

runs:
  using: composite
  steps:
  - run: $find = ${{ inputs.find }}; $replace = ${{ inputs.replace }}; (Get-Content ${{ inputs.file }}) -replace [regex]::Escape($find), $replace | Set-Content ${{ inputs.file }}
    shell: pwsh
