name: Replace text
description: Replace text
inputs:
  file:
    description: File path
    required: true
  find:
    description: Text to find
    required: true
  replace:
    description: Text to replace
    required: true

runs:
  using: composite
  steps:
  - run: |
      $find = ${{ inputs.find }}
      $replace = ${{ inputs.replace }}
      $content = Get-Content ${{ inputs.file }} -raw
      for ($i = 0; $i -lt $find.length; $i++) {
        $content = $content -replace ($find[$i] -replace [Environment]::NewLine, "`n"), $replace[$i]
      }
      Set-Content ${{ inputs.file }} $content
    shell: pwsh
