name: DviJigen
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      uses: actions/checkout@v4
      with:
        repository: godotengine/godot
        submodules: recursive
      uses: actions/cache/restore@v4
        with:
          path: ${{github.workspace}}/.scons-cache/
          key: ${{inputs.cache-name}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{inputs.cache-name}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{inputs.cache-name}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}
            ${{inputs.cache-name}}-${{env.GODOT_BASE_BRANCH}}-refs/heads/${{env.GODOT_BASE_BRANCH}}
            ${{inputs.cache-name}}-${{env.GODOT_BASE_BRANCH}}
