name: DviJigen
on:
  workflow_dispatch:
    inputs:
      godot-release:
        description: Godot release
        default: 4.3-stable
        required: true
      scons-flags:
        description: SCons flags
        default: target=editor use_mingw=yes production=yes optimize=speed module_text_server_adv_enabled=no module_text_server_fb_enabled=yes
        required: true
env:
  cache-name: windows-editor
  GODOT_BASE_BRANCH: ${{ inputs.godot-release }}
concurrency:
  group: ci-${{ github.actor }}-${{ github.head_ref || github.run_number }}-${{ github.ref }}-windows
  cancel-in-progress: true
jobs:
  compile:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: godotengine/godot
        ref: ${{ inputs.godot-release }}
        submodules: recursive
    - uses: actions/checkout@v4
      with:
        path: DviJigen
    - uses: ./DviJigen/.github/actions/replace
      with:
        file: ./SConstruct
        find: |
          homareadachi, homareadatchi
        replace: |
          homareatanmay, homarextanmay
    - uses: ./.github/actions/godot-cache-restore
      with:
        cache-name: ${{ env.cache-name }}
      continue-on-error: true
    - run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
        Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
        scoop install gcc python scons make mingw
        scons ${{ inputs.scons-flags }}
    - uses: ./.github/actions/godot-cache-save
      with:
        cache-name: ${{ env.cache-name }}
      continue-on-error: true
    - run: Remove-Item bin/* -Include *.exp,*.lib,*.pdb -Force
    - uses: ./.github/actions/upload-artifact
      with:
        name: ${{ env.cache-name }}
