name: DviJigen
on:
  workflow_dispatch:
env:
  cache: ./cache/
  cache-name: windows-editor
  GODOT_BASE_BRANCH: ${{ inputs.godot-release }}
jobs:
  compile:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: godotengine/godot
        ref: ${{ inputs.godot-release }}
        submodules: recursive
    - uses: actions/cache/restore@v4
      with:
        path: ${{ env.cache }}
        key: ${{ env.cache-name }}
      continue-on-error: true
    - run: |
        foreach (
          $file in ('custom.py', 'target = ''editor''
        use_mingw = ''yes''
        production = ''yes''
        lto = ''full''
        optimize = ''speed_trace''
        module_text_server_adv_enabled = ''no''
        module_text_server_fb_enabled = ''yes''
        deprecated = ''no''
        precision = ''double''
        xaudio2 = ''yes''
        warnings = ''extra''
        extra_suffix = ''dvijigen''
        use_precise_math_checks = ''yes''
        steamapi = ''yes''
        target_win_version = ''0x0a00''
        windows_subsystem = ''console''
        use_static_cpp = ''no''
        # use_asan = ''yes'''),
          ('a', 'a')
        ) {
          out-file ./$($file[0]) -noclobber -value $file[1]
        }
    - run: |
        invoke-restmethod -uri https://get.scoop.sh | invoke-expression
        scoop install gcc python scons make mingw
        scons --help
        '9'
        scons
    - uses: actions/cache/save@v4
      with:
        path: ${{ env.cache }}
        key: ${{ env.cache-name }}
      continue-on-error: true
    - run: Remove-Item bin/* -Include *.exp,*.lib,*.pdb -Force
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ env.cache-name }}
        path: bin/*
