name: DviJigen
on:
  workflow_dispatch:
    inputs:
      godot-release:
        description: Godot release
        default: 4.3-stable
        required: true
      scons-flags:
        description: SCons flags
        default: target=editor use_mingw=yes production=yes lto=full optimize=speed_trace module_text_server_adv_enabled=no module_text_server_fb_enabled=yes deprecated=no precision=double xaudio2=yes d3d12=no verbose=yes warnings=extra extra_suffix=dvijigen use_precise_math_checks=yes steamapi=yes target_win_version=0x0A00 windows_subsystem=console use_static_cpp=no use_asan=yes
        required: true
env:
  scons-cache: ./scons-cache/
  cache-name: windows-editor
  GODOT_BASE_BRANCH: ${{ inputs.godot-release }}
concurrency:
  group: ci-${{ github.actor }}-${{ github.head_ref || github.run_number }}-${{ github.ref }}-windows
  cancel-in-progress: true
jobs:
  compile:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: godotengine/godot
        ref: ${{ inputs.godot-release }}
        submodules: recursive
    - uses: actions/cache/restore@v4
      with:
        path: ${{ env.scons-cache }}
        key: ${{ env.cache-name }}
      continue-on-error: true
    - run: |
        Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
        scoop install gcc python scons make mingw
        scons --help
        scons ${{ inputs.scons-flags }}
    - uses: actions/cache/save@v4
      with:
        path: ${{ env.scons-cache }}
        key: ${{ env.cache-name }}
      continue-on-error: true
    - run: Remove-Item bin/* -Include *.exp,*.lib,*.pdb -Force
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ env.cache-name }}
        path: bin/*
