name: DviJigen
on:
  workflow_dispatch:
env:
  scons-cache: ${{github.workspace}}/.scons-cache/
  cache-name: ${{github.job}}
  GODOT_BASE_BRANCH: 4.3-stable
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: godotengine/godot
        ref: ${{env.GODOT_BASE_BRANCH}}
        submodules: recursive
    - uses: actions/checkout@v4
      with:
        path: DviJigen
    - uses: ./DviJigen/.github/actions/replace
      with:
        file: ./SConstruct
        find: |
          'print_error("Build option `disable_3d=yes` cannot be used for editor builds, only for export template builds.")'
        #        Exit(255)'
        replace: |
          '// if env.editor_build:
                // print_error("Build option `disable_3d=yes` cannot be used for editor builds, only for export template builds.")
                // Exit(255)'
    - uses: actions/cache/restore@v4
      with:
        path: ${{env.scons-cache}}
        key: ${{env.cache-name}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
        restore-keys: |
          ${{env.cache-name}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          ${{env.cache-name}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}
          ${{env.cache-name}}-${{env.GODOT_BASE_BRANCH}}-refs/heads/${{env.GODOT_BASE_BRANCH}}
          ${{env.cache-name}}-${{env.GODOT_BASE_BRANCH}}
    -  run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
        Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
        scoop install gcc python scons make mingw
        scons target=editor use_mingw=yes production=yes lto=full optimize=speed module_text_server_adv_enabled=no module_text_server_fb_enabled=yes disable_3d=yes
    - uses: actions/cache/save@v4
      with:
        path: ${{env.scons-cache}}
        key: ${{env.cache-name}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
    - run: Remove-Item bin/* -Include *.exp,*.lib,*.pdb -Force
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ github.job }}
        path: bin/*
