name: DviJigen
on:
  workflow_dispatch:
env:
  cache: ./cache/
  name: 4.3-stable
jobs:
  compile:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: godotengine/godot
        ref: ${{ env.name }}
        submodules: recursive
    - uses: actions/cache/restore@v4
      with:
        path: ${{ env.cache }}
        key: ${{ env.name }}
      continue-on-error: true
    - run: >
        foreach (
          $file in ('custom.py', '# target = ''editor''[Environment]::NewLine
        # use_mingw = ''yes''[Environment]::NewLine
        # use_llvm = ''yes''[Environment]::NewLine
        # production = ''yes''[Environment]::NewLine
        # lto = ''full''[Environment]::NewLine
        # optimize = ''speed_trace''[Environment]::NewLine
        # module_text_server_adv_enabled = ''no''[Environment]::NewLine
        # module_text_server_fb_enabled = ''yes''[Environment]::NewLine
        # deprecated = ''no''[Environment]::NewLine
        # precision = ''double''[Environment]::NewLine
        # xaudio2 = ''yes''[Environment]::NewLine
        # warnings = ''extra''[Environment]::NewLine
        # extra_suffix = ''${{ github.repository }}''.split(''/'')[-1][Environment]::NewLine
        # use_precise_math_checks = ''yes''[Environment]::NewLine
        # steamapi = ''yes''[Environment]::NewLine
        # target_win_version = ''0x0a00''[Environment]::NewLine
        # windows_subsystem = ''console''[Environment]::NewLine
        # use_static_cpp = ''no''[Environment]::NewLine
        # use_asan = ''yes'''),
          ('a', 'a')
        ) {
          out-file ./$($file[0]) -noclobber -inputobject $file[1]
        }
    - run: |
        invoke-expression (invoke-restmethod -uri https://get.scoop.sh)
        scoop install gcc python scons make mingw
        scons --help
        scons target=editor use_mingw=yes production=yes lto=full optimize=speed_trace module_text_server_adv_enabled=no module_text_server_fb_enabled=yes
    - uses: actions/cache/save@v4
      with:
        path: ${{ env.cache }}
        key: ${{ env.name }}
      continue-on-error: true
    - run: Remove-Item bin/* -Include *.exp,*.lib,*.pdb -Force
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ env.name }}
        path: bin/*
