on:
  workflow_dispatch:
env:
  SCONS_CACHE: ${{ github.workspace }}/.scons-cache/
  SCONS_CACHE_LIMIT: 4096
  GODOT_BASE_BRANCH: 4.3
jobs:
  compile:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: godotengine/godot
        ref: ${{ env.GODOT_BASE_BRANCH }}
        submodules: recursive
    - uses: ./.github/actions/godot-cache-restore
      with:
        scons-cache: ${{ env.SCONS_CACHE }}
      continue-on-error: true
    - run: |
        foreach ($file in
          ('scene/2d/physics/entity_2d.h', '#ifndef ENTITY_2D_H
        #define ENTITY_2D_H

        #include "scene/2d/node_2d.h"

        class Entity2D : public Node2D {
        	GDCLASS(Entity2D, Node2D);

        private:
          String entity_name;

        protected:
        	static void _bind_methods();

        public:
        	void set_entity_name(const String &p_string);
        	String get_entity_name() const;

        	Entity2D();
        	~Entity2D();
        };

        #endif // Entity_2D_H'),
        ('scene/2d/physics/entity_2d.cpp', '#include "entity_2d.h"

        void Entity2D::set_entity_name(const String &p_string) {
        	entity_name = p_string;
        }

        String Entity2D::get_entity_name() const {
        	return entity_name;
        }

        void Entity2D::_bind_methods() {
        	ClassDB::bind_method(D_METHOD("set_entity_name", "entity"), &Entity2D::set_entity_name);
        	ClassDB::bind_method(D_METHOD("get_entity_name"), &Entity2D::get_entity_name);

        	ADD_GROUP("Entity", "entity_");
        	ADD_PROPERTY(PropertyInfo(Variant::STRING, "entity_name", PROPERTY_HINT_MULTILINE_TEXT), "set_entity_name", "get_entity_name");
        }

        Entity2D::Entity2D() {}

        Entity2D::~Entity2D() {}')
        ) { out-file ./$($file[0]) -noclobber -inputobject ($file[1] -replace [Environment]::NewLine, "`n") }

        foreach (
          $file in @{
            'scene/2d/physics/collision_object_2d.h' = ('node', 'physics/entity'), ('Node', 'Entity')
            'scene/register_scene_types.cpp' = , ('CollisionObject', 'Entity2D);
        	GDREGISTER_ABSTRACT_CLASS(CollisionObject')
            'modules/gdscript/gdscript_tokenizer.cpp' =
              ('P, KEYWORD)     \', 'P, KEYWORD)         \
        	KEYWORD_GROUP(U''फ'')                     \
        	KEYWORD(U"फलन", Token::FUNC)            \'),
              ('MAX_KEYWORD_LENGTH 10', 'MAX_KEYWORD_LENGTH 108'),
              ('

        	if (!only_ascii) {
        		// Kept here in case the order with push_error matters.
        		Token id = make_identifier(name);

        #ifdef DEBUG_ENABLED
        		// Additional checks for identifiers but only in debug and if it''s available in TextServer.
        		if (TS->has_feature(TextServer::FEATURE_UNICODE_SECURITY)) {
        			int64_t confusable = TS->is_confusable(name, keyword_list);
        			if (confusable >= 0) {
        				push_error(vformat(R"(Identifier "%s" is visually similar to the GDScript keyword "%s" and thus not allowed.)", name, keyword_list[confusable]));
        			}
        		}
        #endif // DEBUG_ENABLED

        		// Cannot be a keyword, as keywords are ASCII only.
        		return id;
        	}', '')
          }.getenumerator()
        ) {
          $content = get-content $file.key -raw
          for ($i = 0; $i -lt $file.value.length; $i++) {
            $content = $content -creplace [Regex]::Escape(($file.value[$i][0] -replace [Environment]::NewLine, "`n")), ($file.value[$i][1] -replace [Environment]::NewLine, "`n")
          }
          set-content $file.key $content
          get-content $file.key -raw
        }
        invoke-expression (invoke-restmethod -uri https://get.scoop.sh)
        scoop install gcc python scons make mingw
        scons use_mingw=yes production=yes lto=full optimize=speed_trace steamapi=yes deprecated=no target_win_version=0x0a00 windows_subsystem=console precision=double use_precise_math_checks=yes use_static_cpp=no use_asan=yes warnings=extra module_text_server_adv_enabled=no module_text_server_fb_enabled=yes module_camera_enabled=no module_mobile_vr_enabled=no module_openxr_enabled=no module_webxr_enabled=no
    - uses: ./.github/actions/godot-cache-save
      with:
        scons-cache: ${{ env.SCONS_CACHE }}
      continue-on-error: true
    - run: remove-item bin/* -include *.exp,*.lib,*.pdb -force
    - uses: ./.github/actions/upload-artifact
      with:
        name: ${{ env.GODOT_BASE_BRANCH }}
