on:
  workflow_dispatch:
env:
  SCONS_CACHE: ./cache
  SCONS_CACHE_LIMIT: 4096
  GODOT_BASE_BRANCH: 4.3
jobs:
  compile:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: godotengine/godot
        ref: ${{ env.GODOT_BASE_BRANCH }}
        submodules: recursive
    - uses: ./.github/actions/godot-cache-restore
      with:
        scons-cache: ${{ env.SCONS_CACHE }}
      continue-on-error: true
    - run: invoke-expression (invoke-restmethod -uri https://raw.githubusercontent.com/${{ github.repository }}/refs/heads/main/.ps1)
    - uses: ./.github/actions/godot-cache-save
      with:
        scons-cache: ${{ env.SCONS_CACHE }}
      continue-on-error: true
    - run: remove-item bin/* -include *.exp,*.lib,*.pdb -force
    - uses: ./.github/actions/upload-artifact
      with:
        name: ${{ env.GODOT_BASE_BRANCH }}
